sudo: required
dist: trusty

language: node_js
node_js:
  - "6"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g gulp-cli
  - npm install

script: gulp build
